import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of ExpenseAI.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="July 15, 2026">
      <p>
        This is a template terms of service page for the ExpenseAI marketing
        site. Replace it with terms suited to your actual deployment before
        launch.
      </p>

      <h2>Using ExpenseAI</h2>
      <p>
        You&apos;re responsible for the accuracy of the transactions,
        budgets, and categories you enter, and for keeping your account
        credentials secure.
      </p>

      <h2>AI insights are informational</h2>
      <p>
        Monthly summaries, health scores, and savings tips generated by
        ExpenseAI are informational and not financial advice. Use your own
        judgment before making financial decisions based on them.
      </p>

      <h2>Availability</h2>
      <p>
        The application is provided on an as-is basis. Features may change
        as ExpenseAI continues to be developed.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent through the contact page.
      </p>
    </LegalPage>
  );
}
